# Generated by Django 3.2.16 on 2023-10-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0002_rename_freebeds_room_busybeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalstaff',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='social/images'),
        ),
    ]
